# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
  branches:
    include:
    - main

variables:
- group: varg_plain
- group: varg_secret

pool:
  vmImage: ubuntu-latest

steps:
- script: echo $(varg_plain_1)  && echo $(in_pipe_var)
  displayName: 'Run a one-line script'
